<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class General extends Admin_Controller implements ControllerInterface{

	public function __construct(){
		parent::__construct();
		$this->title = 'General';
		$this->controller = 'general';
		$this->load->model('Setting_model', 'setting');
		$this->redirect_url = base_url_admin().'general';
	}

	public function index(){
		$data = array();
		$data['title'] 		= 'General Setting';
		$data['content'] 	= 'content/setting/general';
		$datas 	= $this->setting->get_all();
		$data['datas'] = array();
		foreach ($datas as $i => $v) {
			$data['datas'][$v['name']] = $v['value'];
		}
		$data['timezones'] = $this->list_timezone();

		$this->template($data);
	}

	public function update(){
		$state = $this->input->get('state');
		if($state == false){
			$post = $this->input->post();
			$data = array();
			$no = 0;
			foreach ($post as $i => $v) {
				$data[$no] = array('name' => $i, 'value' => $v);
				$no++;
			}

			if($this->setting->update_batch($data, 'name')){
				$this->session->set_flashdata('notif_status', true);
				$this->session->set_flashdata('notif_msg', 'Save setting general success');
			}else{
				$this->session->set_flashdata('notif_status', false);
				$this->session->set_flashdata('notif_msg', 'Save setting general failed');
			}
		}else{
			$config['upload_path'] 		= getcwd().'/assets/img';
			$config['file_name'] 		= 'logo';
			$config['allowed_types'] 	= 'gif|jpg|png';
			$config['max_size'] 		= 2048;
			$config['max_width'] 		= 250;
			$config['max_height'] 		= 250;

			$this->load->library('upload', $config);

			if ($this->upload->do_upload('logo')){
				$data = array('name' => 'logo', 'value' => base_url().'assets/img/'.$this->upload->data('file_name'));
				$this->setting->update_by(array('name' => 'logo'), $data);
				$this->session->set_flashdata('notif_status', true);
				$this->session->set_flashdata('notif_msg', 'Upload logo success');
			}
			else{
				$this->session->set_flashdata('notif_status', false);
				$this->session->set_flashdata('notif_msg', $this->upload->display_errors());
			}
		}
		redirect($this->redirect_url);
	}

	public function add(){}
	public function edit(){}
	public function insert(){}
	public function delete(){}

	public function list_timezone(){
		$time_zone = array(
			"Africa" => array(
				array("Africa/Abidjan","Abidjan"),
				array("Africa/Accra","Accra"),
				array("Africa/Addis_Ababa","Addis Ababa"),
				array("Africa/Algiers","Algiers"),
				array("Africa/Asmara","Asmara"),
				array("Africa/Bamako","Bamako"),
				array("Africa/Bangui","Bangui"),
				array("Africa/Banjul","Banjul"),
				array("Africa/Bissau","Bissau"),
				array("Africa/Blantyre","Blantyre"),
				array("Africa/Brazzaville","Brazzaville"),
				array("Africa/Bujumbura","Bujumbura"),
				array("Africa/Cairo","Cairo"),
				array("Africa/Casablanca","Casablanca"),
				array("Africa/Ceuta","Ceuta"),
				array("Africa/Conakry","Conakry"),
				array("Africa/Dakar","Dakar"),
				array("Africa/Dar_es_Salaam","Dar es Salaam"),
				array("Africa/Djibouti","Djibouti"),
				array("Africa/Douala","Douala"),
				array("Africa/El_Aaiun","El Aaiun"),
				array("Africa/Freetown","Freetown"),
				array("Africa/Gaborone","Gaborone"),
				array("Africa/Harare","Harare"),
				array("Africa/Johannesburg","Johannesburg"),
				array("Africa/Juba","Juba"),
				array("Africa/Kampala","Kampala"),
				array("Africa/Khartoum","Khartoum"),
				array("Africa/Kigali","Kigali"),
				array("Africa/Kinshasa","Kinshasa"),
				array("Africa/Lagos","Lagos"),
				array("Africa/Libreville","Libreville"),
				array("Africa/Lome","Lome"),
				array("Africa/Luanda","Luanda"),
				array("Africa/Lubumbashi","Lubumbashi"),
				array("Africa/Lusaka","Lusaka"),
				array("Africa/Malabo","Malabo"),
				array("Africa/Maputo","Maputo"),
				array("Africa/Maseru","Maseru"),
				array("Africa/Mbabane","Mbabane"),
				array("Africa/Mogadishu","Mogadishu"),
				array("Africa/Monrovia","Monrovia"),
				array("Africa/Nairobi","Nairobi"),
				array("Africa/Ndjamena","Ndjamena"),
				array("Africa/Niamey","Niamey"),
				array("Africa/Nouakchott","Nouakchott"),
				array("Africa/Ouagadougou","Ouagadougou"),
				array("Africa/Porto-Novo","Porto-Novo"),
				array("Africa/Sao_Tome","Sao Tome"),
				array("Africa/Tripoli","Tripoli"),
				array("Africa/Tunis","Tunis"),
				array("Africa/Windhoek","Windhoek")
			),
			"America" => array(
				array("America/Adak","Adak"),
				array("America/Anchorage","Anchorage"),
				array("America/Anguilla","Anguilla"),
				array("America/Antigua","Antigua"),
				array("America/Araguaina","Araguaina"),
				array("America/Argentina/Buenos_Aires","Argentina - Buenos Aires"),
				array("America/Argentina/Catamarca","Argentina - Catamarca"),
				array("America/Argentina/Cordoba","Argentina - Cordoba"),
				array("America/Argentina/Jujuy","Argentina - Jujuy"),
				array("America/Argentina/La_Rioja","Argentina - La Rioja"),
				array("America/Argentina/Mendoza","Argentina - Mendoza"),
				array("America/Argentina/Rio_Gallegos","Argentina - Rio Gallegos"),
				array("America/Argentina/Salta","Argentina - Salta"),
				array("America/Argentina/San_Juan","Argentina - San Juan"),
				array("America/Argentina/San_Luis","Argentina - San Luis"),
				array("America/Argentina/Tucuman","Argentina - Tucuman"),
				array("America/Argentina/Ushuaia","Argentina - Ushuaia"),
				array("America/Aruba","Aruba"),
				array("America/Asuncion","Asuncion"),
				array("America/Atikokan","Atikokan"),
				array("America/Bahia","Bahia"),
				array("America/Bahia_Banderas","Bahia Banderas"),
				array("America/Barbados","Barbados"),
				array("America/Belem","Belem"),
				array("America/Belize","Belize"),
				array("America/Blanc-Sablon","Blanc-Sablon"),
				array("America/Boa_Vista","Boa Vista"),
				array("America/Bogota","Bogota"),
				array("America/Boise","Boise"),
				array("America/Cambridge_Bay","Cambridge Bay"),
				array("America/Campo_Grande","Campo Grande"),
				array("America/Cancun","Cancun"),
				array("America/Caracas","Caracas"),
				array("America/Cayenne","Cayenne"),
				array("America/Cayman","Cayman"),
				array("America/Chicago","Chicago"),
				array("America/Chihuahua","Chihuahua"),
				array("America/Costa_Rica","Costa Rica"),
				array("America/Creston","Creston"),
				array("America/Cuiaba","Cuiaba"),
				array("America/Curacao","Curacao"),
				array("America/Danmarkshavn","Danmarkshavn"),
				array("America/Dawson","Dawson"),
				array("America/Dawson_Creek","Dawson Creek"),
				array("America/Denver","Denver"),
				array("America/Detroit","Detroit"),
				array("America/Dominica","Dominica"),
				array("America/Edmonton","Edmonton"),
				array("America/Eirunepe","Eirunepe"),
				array("America/El_Salvador","El Salvador"),
				array("America/Fortaleza","Fortaleza"),
				array("America/Glace_Bay","Glace Bay"),
				array("America/Godthab","Godthab"),
				array("America/Goose_Bay","Goose Bay"),
				array("America/Grand_Turk","Grand Turk"),
				array("America/Grenada","Grenada"),
				array("America/Guadeloupe","Guadeloupe"),
				array("America/Guatemala","Guatemala"),
				array("America/Guayaquil","Guayaquil"),
				array("America/Guyana","Guyana"),
				array("America/Halifax","Halifax"),
				array("America/Havana","Havana"),
				array("America/Hermosillo","Hermosillo"),
				array("America/Indiana/Indianapolis","Indiana - Indianapolis"),
				array("America/Indiana/Knox","Indiana - Knox"),
				array("America/Indiana/Marengo","Indiana - Marengo"),
				array("America/Indiana/Petersburg","Indiana - Petersburg"),
				array("America/Indiana/Tell_City","Indiana - Tell City"),
				array("America/Indiana/Vevay","Indiana - Vevay"),
				array("America/Indiana/Vincennes","Indiana - Vincennes"),
				array("America/Indiana/Winamac","Indiana - Winamac"),
				array("America/Inuvik","Inuvik"),
				array("America/Iqaluit","Iqaluit"),
				array("America/Jamaica","Jamaica"),
				array("America/Juneau","Juneau"),
				array("America/Kentucky/Louisville","Kentucky - Louisville"),
				array("America/Kentucky/Monticello","Kentucky - Monticello"),
				array("America/Kralendijk","Kralendijk"),
				array("America/La_Paz","La Paz"),
				array("America/Lima","Lima"),
				array("America/Los_Angeles","Los Angeles"),
				array("America/Lower_Princes","Lower Princes"),
				array("America/Maceio","Maceio"),
				array("America/Managua","Managua"),
				array("America/Manaus","Manaus"),
				array("America/Marigot","Marigot"),
				array("America/Martinique","Martinique"),
				array("America/Matamoros","Matamoros"),
				array("America/Mazatlan","Mazatlan"),
				array("America/Menominee","Menominee"),
				array("America/Merida","Merida"),
				array("America/Metlakatla","Metlakatla"),
				array("America/Mexico_City","Mexico City"),
				array("America/Miquelon","Miquelon"),
				array("America/Moncton","Moncton"),
				array("America/Monterrey","Monterrey"),
				array("America/Montevideo","Montevideo"),
				array("America/Montserrat","Montserrat"),
				array("America/Nassau","Nassau"),
				array("America/New_York","New York"),
				array("America/Nipigon","Nipigon"),
				array("America/Nome","Nome"),
				array("America/Noronha","Noronha"),
				array("America/North_Dakota/Beulah","North Dakota - Beulah"),
				array("America/North_Dakota/Center","North Dakota - Center"),
				array("America/North_Dakota/New_Salem","North Dakota - New Salem"),
				array("America/Ojinaga","Ojinaga"),
				array("America/Panama","Panama"),
				array("America/Pangnirtung","Pangnirtung"),
				array("America/Paramaribo","Paramaribo"),
				array("America/Phoenix","Phoenix"),
				array("America/Port-au-Prince","Port-au-Prince"),
				array("America/Port_of_Spain","Port of Spain"),
				array("America/Porto_Velho","Porto Velho"),
				array("America/Puerto_Rico","Puerto Rico"),
				array("America/Rainy_River","Rainy River"),
				array("America/Rankin_Inlet","Rankin Inlet"),
				array("America/Recife","Recife"),
				array("America/Regina","Regina"),
				array("America/Resolute","Resolute"),
				array("America/Rio_Branco","Rio Branco"),
				array("America/Santa_Isabel","Santa Isabel"),
				array("America/Santarem","Santarem"),
				array("America/Santiago","Santiago"),
				array("America/Santo_Domingo","Santo Domingo"),
				array("America/Sao_Paulo","Sao Paulo"),
				array("America/Scoresbysund","Scoresbysund"),
				array("America/Sitka","Sitka"),
				array("America/St_Barthelemy","St Barthelemy"),
				array("America/St_Johns","St Johns"),
				array("America/St_Kitts","St Kitts"),
				array("America/St_Lucia","St Lucia"),
				array("America/St_Thomas","St Thomas"),
				array("America/St_Vincent","St Vincent"),
				array("America/Swift_Current","Swift Current"),
				array("America/Tegucigalpa","Tegucigalpa"),
				array("America/Thule","Thule"),
				array("America/Thunder_Bay","Thunder Bay"),
				array("America/Tijuana","Tijuana"),
				array("America/Toronto","Toronto"),
				array("America/Tortola","Tortola"),
				array("America/Vancouver","Vancouver"),
				array("America/Whitehorse","Whitehorse"),
				array("America/Winnipeg","Winnipeg"),
				array("America/Yakutat","Yakutat"),
				array("America/Yellowknife","Yellowknife")
			),
			"Antarctica" => array(
				array("Antarctica/Casey","Casey"),
				array("Antarctica/Davis","Davis"),
				array("Antarctica/DumontDUrville","DumontDUrville"),
				array("Antarctica/Macquarie","Macquarie"),
				array("Antarctica/Mawson","Mawson"),
				array("Antarctica/McMurdo","McMurdo"),
				array("Antarctica/Palmer","Palmer"),
				array("Antarctica/Rothera","Rothera"),
				array("Antarctica/Syowa","Syowa"),
				array("Antarctica/Troll","Troll"),
				array("Antarctica/Vostok","Vostok"),
			),
			"Arctic" => array(
				array("Arctic/Longyearbyen","Longyearbyen"),
			),
			"Asia" => array(
				array("Asia/Aden","Aden"),
				array("Asia/Almaty","Almaty"),
				array("Asia/Amman","Amman"),
				array("Asia/Anadyr","Anadyr"),
				array("Asia/Aqtau","Aqtau"),
				array("Asia/Aqtobe","Aqtobe"),
				array("Asia/Ashgabat","Ashgabat"),
				array("Asia/Baghdad","Baghdad"),
				array("Asia/Bahrain","Bahrain"),
				array("Asia/Baku","Baku"),
				array("Asia/Bangkok","Bangkok"),
				array("Asia/Beirut","Beirut"),
				array("Asia/Bishkek","Bishkek"),
				array("Asia/Brunei","Brunei"),
				array("Asia/Chita","Chita"),
				array("Asia/Choibalsan","Choibalsan"),
				array("Asia/Colombo","Colombo"),
				array("Asia/Damascus","Damascus"),
				array("Asia/Dhaka","Dhaka"),
				array("Asia/Dili","Dili"),
				array("Asia/Dubai","Dubai"),
				array("Asia/Dushanbe","Dushanbe"),
				array("Asia/Gaza","Gaza"),
				array("Asia/Hebron","Hebron"),
				array("Asia/Ho_Chi_Minh","Ho Chi Minh"),
				array("Asia/Hong_Kong","Hong Kong"),
				array("Asia/Hovd","Hovd"),
				array("Asia/Irkutsk","Irkutsk"),
				array("Asia/Jakarta","Jakarta"),
				array("Asia/Jayapura","Jayapura"),
				array("Asia/Jerusalem","Jerusalem"),
				array("Asia/Kabul","Kabul"),
				array("Asia/Kamchatka","Kamchatka"),
				array("Asia/Karachi","Karachi"),
				array("Asia/Kathmandu","Kathmandu"),
				array("Asia/Khandyga","Khandyga"),
				array("Asia/Kolkata","Kolkata"),
				array("Asia/Krasnoyarsk","Krasnoyarsk"),
				array("Asia/Kuala_Lumpur","Kuala Lumpur"),
				array("Asia/Kuching","Kuching"),
				array("Asia/Kuwait","Kuwait"),
				array("Asia/Macau","Macau"),
				array("Asia/Magadan","Magadan"),
				array("Asia/Makassar","Makassar"),
				array("Asia/Manila","Manila"),
				array("Asia/Muscat","Muscat"),
				array("Asia/Nicosia","Nicosia"),
				array("Asia/Novokuznetsk","Novokuznetsk"),
				array("Asia/Novosibirsk","Novosibirsk"),
				array("Asia/Omsk","Omsk"),
				array("Asia/Oral","Oral"),
				array("Asia/Phnom_Penh","Phnom Penh"),
				array("Asia/Pontianak","Pontianak"),
				array("Asia/Pyongyang","Pyongyang"),
				array("Asia/Qatar","Qatar"),
				array("Asia/Qyzylorda","Qyzylorda"),
				array("Asia/Rangoon","Rangoon"),
				array("Asia/Riyadh","Riyadh"),
				array("Asia/Sakhalin","Sakhalin"),
				array("Asia/Samarkand","Samarkand"),
				array("Asia/Seoul","Seoul"),
				array("Asia/Shanghai","Shanghai"),
				array("Asia/Singapore","Singapore"),
				array("Asia/Srednekolymsk","Srednekolymsk"),
				array("Asia/Taipei","Taipei"),
				array("Asia/Tashkent","Tashkent"),
				array("Asia/Tbilisi","Tbilisi"),
				array("Asia/Tehran","Tehran"),
				array("Asia/Thimphu","Thimphu"),
				array("Asia/Tokyo","Tokyo"),
				array("Asia/Ulaanbaatar","Ulaanbaatar"),
				array("Asia/Urumqi","Urumqi"),
				array("Asia/Ust-Nera","Ust-Nera"),
				array("Asia/Vientiane","Vientiane"),
				array("Asia/Vladivostok","Vladivostok"),
				array("Asia/Yakutsk","Yakutsk"),
				array("Asia/Yekaterinburg","Yekaterinburg"),
				array("Asia/Yerevan","Yerevan"),
			),
			"Atlantic" => array(
				array("Atlantic/Azores","Azores"),
				array("Atlantic/Bermuda","Bermuda"),
				array("Atlantic/Canary","Canary"),
				array("Atlantic/Cape_Verde","Cape Verde"),
				array("Atlantic/Faroe","Faroe"),
				array("Atlantic/Madeira","Madeira"),
				array("Atlantic/Reykjavik","Reykjavik"),
				array("Atlantic/South_Georgia","South Georgia"),
				array("Atlantic/Stanley","Stanley"),
				array("Atlantic/St_Helena","St Helena"),
			),
			"Australia" => array(
				array("Australia/Adelaide","Adelaide"),
				array("Australia/Brisbane","Brisbane"),
				array("Australia/Broken_Hill","Broken Hill"),
				array("Australia/Currie","Currie"),
				array("Australia/Darwin","Darwin"),
				array("Australia/Eucla","Eucla"),
				array("Australia/Hobart","Hobart"),
				array("Australia/Lindeman","Lindeman"),
				array("Australia/Lord_Howe","Lord Howe"),
				array("Australia/Melbourne","Melbourne"),
				array("Australia/Perth","Perth"),
				array("Australia/Sydney","Sydney"),
			),
			"Europe" => array(
				array("Europe/Amsterdam","Amsterdam"),
				array("Europe/Andorra","Andorra"),
				array("Europe/Athens","Athens"),
				array("Europe/Belgrade","Belgrade"),
				array("Europe/Berlin","Berlin"),
				array("Europe/Bratislava","Bratislava"),
				array("Europe/Brussels","Brussels"),
				array("Europe/Bucharest","Bucharest"),
				array("Europe/Budapest","Budapest"),
				array("Europe/Busingen","Busingen"),
				array("Europe/Chisinau","Chisinau"),
				array("Europe/Copenhagen","Copenhagen"),
				array("Europe/Dublin","Dublin"),
				array("Europe/Gibraltar","Gibraltar"),
				array("Europe/Guernsey","Guernsey"),
				array("Europe/Helsinki","Helsinki"),
				array("Europe/Isle_of_Man","Isle of Man"),
				array("Europe/Istanbul","Istanbul"),
				array("Europe/Jersey","Jersey"),
				array("Europe/Kaliningrad","Kaliningrad"),
				array("Europe/Kiev","Kiev"),
				array("Europe/Lisbon","Lisbon"),
				array("Europe/Ljubljana","Ljubljana"),
				array("Europe/London","London"),
				array("Europe/Luxembourg","Luxembourg"),
				array("Europe/Madrid","Madrid"),
				array("Europe/Malta","Malta"),
				array("Europe/Mariehamn","Mariehamn"),
				array("Europe/Minsk","Minsk"),
				array("Europe/Monaco","Monaco"),
				array("Europe/Moscow","Moscow"),
				array("Europe/Oslo","Oslo"),
				array("Europe/Paris","Paris"),
				array("Europe/Podgorica","Podgorica"),
				array("Europe/Prague","Prague"),
				array("Europe/Riga","Riga"),
				array("Europe/Rome","Rome"),
				array("Europe/Samara","Samara"),
				array("Europe/San_Marino","San Marino"),
				array("Europe/Sarajevo","Sarajevo"),
				array("Europe/Simferopol","Simferopol"),
				array("Europe/Skopje","Skopje"),
				array("Europe/Sofia","Sofia"),
				array("Europe/Stockholm","Stockholm"),
				array("Europe/Tallinn","Tallinn"),
				array("Europe/Tirane","Tirane"),
				array("Europe/Uzhgorod","Uzhgorod"),
				array("Europe/Vaduz","Vaduz"),
				array("Europe/Vatican","Vatican"),
				array("Europe/Vienna","Vienna"),
				array("Europe/Vilnius","Vilnius"),
				array("Europe/Volgograd","Volgograd"),
				array("Europe/Warsaw","Warsaw"),
				array("Europe/Zagreb","Zagreb"),
				array("Europe/Zaporozhye","Zaporozhye"),
				array("Europe/Zurich","Zurich"),
			),
			"Indian" => array(
				array("Indian/Antananarivo","Antananarivo"),
				array("Indian/Chagos","Chagos"),
				array("Indian/Christmas","Christmas"),
				array("Indian/Cocos","Cocos"),
				array("Indian/Comoro","Comoro"),
				array("Indian/Kerguelen","Kerguelen"),
				array("Indian/Mahe","Mahe"),
				array("Indian/Maldives","Maldives"),
				array("Indian/Mauritius","Mauritius"),
				array("Indian/Mayotte","Mayotte"),
				array("Indian/Reunion","Reunion"),
			),
			"Pacific" => array(
				array("Pacific/Apia","Apia"),
				array("Pacific/Auckland","Auckland"),
				array("Pacific/Bougainville","Bougainville"),
				array("Pacific/Chatham","Chatham"),
				array("Pacific/Chuuk","Chuuk"),
				array("Pacific/Easter","Easter"),
				array("Pacific/Efate","Efate"),
				array("Pacific/Enderbury","Enderbury"),
				array("Pacific/Fakaofo","Fakaofo"),
				array("Pacific/Fiji","Fiji"),
				array("Pacific/Funafuti","Funafuti"),
				array("Pacific/Galapagos","Galapagos"),
				array("Pacific/Gambier","Gambier"),
				array("Pacific/Guadalcanal","Guadalcanal"),
				array("Pacific/Guam","Guam"),
				array("Pacific/Honolulu","Honolulu"),
				array("Pacific/Johnston","Johnston"),
				array("Pacific/Kiritimati","Kiritimati"),
				array("Pacific/Kosrae","Kosrae"),
				array("Pacific/Kwajalein","Kwajalein"),
				array("Pacific/Majuro","Majuro"),
				array("Pacific/Marquesas","Marquesas"),
				array("Pacific/Midway","Midway"),
				array("Pacific/Nauru","Nauru"),
				array("Pacific/Niue","Niue"),
				array("Pacific/Norfolk","Norfolk"),
				array("Pacific/Noumea","Noumea"),
				array("Pacific/Pago_Pago","Pago Pago"),
				array("Pacific/Palau","Palau"),
				array("Pacific/Pitcairn","Pitcairn"),
				array("Pacific/Pohnpei","Pohnpei"),
				array("Pacific/Port_Moresby","Port Moresby"),
				array("Pacific/Rarotonga","Rarotonga"),
				array("Pacific/Saipan","Saipan"),
				array("Pacific/Tahiti","Tahiti"),
				array("Pacific/Tarawa","Tarawa"),
				array("Pacific/Tongatapu","Tongatapu"),
				array("Pacific/Wake","Wake"),
				array("Pacific/Wallis","Wallis"),
			),
			"UTC" => array(
				array("UTC","UTC"),
			),
			"Manual Offsets" => array(
				array("UTC-12","UTC-12"),
				array("UTC-11.5","UTC-11:30"),
				array("UTC-11","UTC-11"),
				array("UTC-10.5","UTC-10:30"),
				array("UTC-10","UTC-10"),
				array("UTC-9.5","UTC-9:30"),
				array("UTC-9","UTC-9"),
				array("UTC-8.5","UTC-8:30"),
				array("UTC-8","UTC-8"),
				array("UTC-7.5","UTC-7:30"),
				array("UTC-7","UTC-7"),
				array("UTC-6.5","UTC-6:30"),
				array("UTC-6","UTC-6"),
				array("UTC-5.5","UTC-5:30"),
				array("UTC-5","UTC-5"),
				array("UTC-4.5","UTC-4:30"),
				array("UTC-4","UTC-4"),
				array("UTC-3.5","UTC-3:30"),
				array("UTC-3","UTC-3"),
				array("UTC-2.5","UTC-2:30"),
				array("UTC-2","UTC-2"),
				array("UTC-1.5","UTC-1:30"),
				array("UTC-1","UTC-1"),
				array("UTC-0.5","UTC-0:30"),
				array("UTC+0","UTC+0"),
				array("UTC+0.5","UTC+0:30"),
				array("UTC+1","UTC+1"),
				array("UTC+1.5","UTC+1:30"),
				array("UTC+2","UTC+2"),
				array("UTC+2.5","UTC+2:30"),
				array("UTC+3","UTC+3"),
				array("UTC+3.5","UTC+3:30"),
				array("UTC+4","UTC+4"),
				array("UTC+4.5","UTC+4:30"),
				array("UTC+5","UTC+5"),
				array("UTC+5.5","UTC+5:30"),
				array("UTC+5.75","UTC+5:45"),
				array("UTC+6","UTC+6"),
				array("UTC+6.5","UTC+6:30"),
				array("UTC+7","UTC+7"),
				array("UTC+7.5","UTC+7:30"),
				array("UTC+8","UTC+8"),
				array("UTC+8.5","UTC+8:30"),
				array("UTC+8.75","UTC+8:45"),
				array("UTC+9","UTC+9"),
				array("UTC+9.5","UTC+9:30"),
				array("UTC+10","UTC+10"),
				array("UTC+10.5","UTC+10:30"),
				array("UTC+11","UTC+11"),
				array("UTC+11.5","UTC+11:30"),
				array("UTC+12","UTC+12"),
				array("UTC+12.75","UTC+12:45"),
				array("UTC+13","UTC+13"),
				array("UTC+13.75","UTC+13:45"),
				array("UTC+14","UTC+14"),
			)
		);
		
		return $time_zone;
	}
}
